issues/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required
from issues import views

urlpatterns = patterns('',
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'issues/login.html'}, name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'template_name': 'issues/logout.html'}, name='logout'),
    url(r'^$', login_required(views.IndexView.as_view()), name='index'),
    url(r'^songs/$', login_required(views.SongIndexView.as_view()), name='song_index'),
    url(r'^new/$', login_required(views.IssueCreate.as_view()), name='new_issue'),
    url(r'^delete/(?P<issue_id>\d+)/$', login_required(views.delete), name='delete'),
    url(r'^songs/delete/(?P<song_id>\d+)/$', login_required(views.delete_song), name='delete_song'),
    url(r'^songs/new/$', login_required(views.SongCreate.as_view(success_url="../")), name='new_song'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^songs/(?P<pk>\d+)/$', login_required(views.SongDetailView.as_view()), name='song_detail'),
    url(r'^(?P<issue_id>\d+)/vote/$', login_required(views.vote), name='vote'),
    url(r'^(?P<issue_id>\d+)/comment/$', login_required(views.comment), name='comment'),
    url(r'^(?P<issue_id>\d+)/delete_comment/(?P<comment_id>\d+)', login_required(views.delete_comment), name='delete_comment'),
    )

octo/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('issues.urls', namespace="issues")),
)

issues/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

import datetime

TYPE_CHOICES = (
    ('Suggestion', 'Suggestion'),
    ('Editing Issue', 'Editing Issue'),
    ('Mix Issue', 'Mix Issue'),
    ('Timing Issue', 'Timing Issue'),
    ('Pitch Issue', 'Pitch Issue'),
    ('Misc.', 'Misc.'),
)
SEVERITY_CHOICES = (
    ('Trivial', 'Trivial'),
    ('Minor', 'Minor'),
    ('Major', 'Major'),
    ('Severe', 'Severe'),
)
STATUS_CHOICES = (
    ('New', 'New'),
    ('Acknowledged', 'Acknowledged'),
    ('Fix Proposed', 'Fix Proposed'),
    ('Resolved', 'Resolved'),
    )
VOTE_CHOICES = (
    ('up', 'up'),
    ('down', 'down'),
    )
ROLE_CHOICES = (
    ('reporter', 'Reporter'),
    ('editor', 'Editor'),
    )


class SiteUser(models.Model):
    def __str__(self):
        return self.user.username

    user = models.ForeignKey(User)
    role = models.CharField(max_length=20, choices=ROLE_CHOICES)
    email_notifications = models.BooleanField(default=True)

class Song(models.Model):
    def __str__(self):
        return self.title

    title = models.CharField(max_length=50, default='')
    notes = models.CharField(max_length=200, default='None')
    url = models.CharField(max_length=500, default='')


class Issue(models.Model):
    def __str__(self):
        return self.title

    def is_new(self):
        return self.status == 'New'

    def timecode(self):
        minutes = self.seconds / 60
        seconds = self.seconds % 60
        return "%d:%02d" % (minutes, seconds)

    is_new.boolean = True
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=1000)
    date = models.DateTimeField(default=datetime.datetime.now())
    typeof = models.CharField(max_length=100, choices=TYPE_CHOICES, default='Suggestion')
    severity = models.CharField(max_length = 100, choices=SEVERITY_CHOICES, default='Trivial')
    status = models.CharField(max_length = 50, choices=STATUS_CHOICES, default='New')
    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)
    song = models.ForeignKey(Song)
    minutes = models.IntegerField(default=0)
    seconds = models.IntegerField(default=0)
    reporter = models.CharField(max_length=30)


class IssueComment(models.Model):
    def __str__(self):
        return self.text

    issue = models.ForeignKey(Issue)
    text = models.CharField(max_length=1000)
    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)
    user = models.CharField(max_length=100)
    date = models.DateTimeField(default=datetime.datetime.now())


class Vote(models.Model):
    def __str__(self):
        return self.user.username + " | " + self.issue.title

    issue = models.ForeignKey(Issue)
    user = models.ForeignKey(User)
    mode = models.CharField(max_length=10, choices=VOTE_CHOICES)

class Subscription(models.Model):
    issue = models.ForeignKey(Issue)
    user = models.ForeignKey(User)

issues/forms.py
from django import forms
from datetime import timedelta
from django.contrib.auth.models import User
import issues.models as models

class IssueForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super(IssueForm, self).__init__(*args, **kwargs)
        self.fields['song'] = forms.ModelChoiceField(queryset=models.Song.objects.all())

    title = forms.CharField(max_length=100)
    description = forms.CharField(label="Description:<br>", widget=forms.widgets.Textarea())
    typeof = forms.ChoiceField(choices=models.TYPE_CHOICES, label="Issue Type")
    severity = forms.ChoiceField(choices=models.SEVERITY_CHOICES, label="Issue Severity")
    song = forms.ChoiceField(choices=((song.id, song) for song in models.Song.objects.all()), label="Song")

    class Meta:
        model = models.Issue
        fields = ('title', 'description', 'typeof', 'severity', 'minutes', 'seconds')
        widgets = {
                'minutes': forms.widgets.NumberInput(attrs={'placeholder': 0, 'maxlength': 2, 'style': 'width:40px'}),
                'seconds': forms.widgets.NumberInput(attrs={'placeholder': 0, 'maxlength': 2, 'style': 'width:40px'}),
                }

class AccountForm(forms.ModelForm):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    username = forms.CharField(max_length=100)
    email = forms.CharField(max_length=100)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

issues/views.py
import datetime

from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.views.generic.base import View
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth import authenticate
from django.contrib.auth.models import User

from issues.models import *
from issues.forms import *
from issues.utils import *

URL = 'https://mod.apalinode.com'

class IndexView(generic.ListView):
    template_name = 'issues/index.html'
    context_object_name = 'issue_recent_list'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['page'] = 'issues'
        return context

    def get_queryset(self):
        return Issue.objects.order_by('-date')

class SongIndexView(generic.ListView):
    template_name = 'issues/index.html'
    context_object_name = 'song_recent_list'

    def get_context_data(self, **kwargs):
        context = super(SongIndexView, self).get_context_data(**kwargs)
        context['page'] = 'songs'
        return context

    def get_queryset(self):
        return Song.objects.order_by('-title')[:25]

class DetailView(generic.DetailView):
    model = Issue
    template_name = 'issues/detail.html'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['page'] = 'issues'
        context['upvoters'] = Vote.objects.filter(issue=context['issue'], mode='up')
        context['downvoters'] = Vote.objects.filter(issue=context['issue'], mode='down')
        context['comments'] = IssueComment.objects.filter(issue=context['issue']).order_by('-date')
        return context

class SongDetailView(generic.DetailView):
    model = Song
    template_name = 'issues/detail.html'

class IssueCreate(generic.CreateView):
    model = Issue
    template_name = 'issues/new.html'

    def get(self, request, *args, **kwargs):
        form = IssueForm(request.user)
        return self.render_to_response({'form': form, 'page': 'issues',})

    def post(self, request, *args, **kwargs):
        form = IssueForm(request.user, request.POST)
        if form.is_valid():
            form.instance.song = Song.objects.get(id=request.POST.get('song'))
            form.instance.reporter = request.user
            form.save()
            Subscription.objects.create(issue=form.instance, user=request.user)
            for user in get_editors():
                new_issue_email(user.user.first_name, user.user.email, URL + reverse('issues:detail', args=(form.instance.id,)))
            return redirect('/')
        return self.render_to_response({'form': form, 'page': 'issues',})

class SongCreate(generic.CreateView):
    model = Song
    fields = ['title', 'notes', 'url']
    template_name = 'issues/new.html'

def delete(request, issue_id):
    issue = get_object_or_404(Issue, pk=issue_id)
    issue.delete()
    return redirect('/')

def delete_song(request, song_id):
    song = get_object_or_404(Song, pk=song_id)
    song.delete()
    return redirect('/songs/')

def comment(request, issue_id):
    issue = get_object_or_404(Issue, pk=issue_id)
    text = request.POST.get('text')
    IssueComment.objects.create(user=request.user, text=text, issue=issue)
    for sub in Subscription.objects.filter(issue=issue):
        issue_comment_email(sub.user.first_name, issue.title, sub.user.email, URL + reverse('issues:detail', args=(issue.id,)), text)
    Subscription.objects.create(issue=issue, user=request.user)
    return redirect('/' + issue_id)

def delete_comment(request, issue_id, comment_id):
    comment = get_object_or_404(IssueComment, pk=comment_id)
    comment.delete()
    return redirect('/' + issue_id)

def vote(request, comment_id):
    if request.user.is_authenticated():
        issue = get_object_or_404(Issue, pk=issue_id)
        vote = Vote.objects.filter(user=request.user, issue=issue)
        if not vote:
            if request.POST.get('voteup', False):
                Vote.objects.create(user=request.user, issue=issue, mode='up')
                issue.upvotes += 1
            elif request.POST.get('votedown', False):
                Vote.objects.create(user=request.user, issue=issue, mode='down')
                issue.downvotes += 1
        else:
            vote = vote[0]
            if vote.mode == 'up':
                if request.POST.get('votedown', False):
                    issue.downvotes += 1
                    issue.upvotes -= 1
                    vote.mode = 'down'
            elif vote.mode == 'down':
                if request.POST.get('voteup', False):
                    issue.downvotes -= 1
                    issue.upvotes += 1
                    vote.mode = 'up'
            vote.save()
        issue.save()
        return HttpResponseRedirect(reverse('issues:detail', args=(issue.id,)))
    else:
        return HttpResponse("You can't vote in this poll.")

issues/templates/issues/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="../../favicon.ico">

        <!-- Bootstrap core CSS -->
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">

        {% block head %}
        <title>MoD</title>
        {% endblock %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    </head>

    <body style="padding-top:60px;">

        <script>
$( document ).ready(function() {
    $('#{{ page }}_nav').addClass('active');
    $('.btn').tooltip();
    {% if issue.song %}
    var clip = $("#song");
    clip.currentTime= {{ issue.minutes }} * 60 + {{ issue.seconds }};
    {% endif %}
});
        </script>
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-headphones"></span> MoD</a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        {% block nav %}
                        <li id="issues_nav"><a href="{% url 'issues:index' %}">Issues</a></li>
                        <li id="songs_nav"><a href="{% url 'issues:song_index' %}">Songs</a></li>
                        {% endblock nav %}
                    </ul>
                    <form class="navbar-form navbar-right">
                        <div class="form-group">
                            Welcome, {{ user }}!
                        </div>
                        <div class="form-group">
                            <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span></button>
                        </div>
                        <a href="{% url 'issues:logout' %}"><button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-off" aria-hidden="true"></span></button></a>
                    </form>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

        <div class="container">

            {% block body %}
            <div class="starter-template">
                <h1>Bootstrap starter template</h1>
                <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
            </div>
            {% endblock %}
        </div><!-- /.container -->
        {% block footer %}
        {% endblock %}


        <!-- Bootstrap core JavaScript
            ================================================== -->
            <!-- Placed at the end of the document so the pages load faster -->
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    </body>
</html>

issues/templates/issues/detail.html
{% extends 'issues/base.html' %}
{% load staticfiles %}
<head>
    {% block head %}
    <title>View Detail</title>
    {% endblock %}
</head>
{% block body %}
<script>
window.onload = function() {
    var clip = document.getElementById("song");
    clip.currentTime= {{ issue.minutes }} * 60 + {{ issue.seconds }};
};
</script>

<div class='details'>
    {% if issue %}
    <h3>{{ issue.title }}</h3>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <div class='detail'>
        <p>Submitted by: <i>{{ issue.reporter }}</i></p>
        <p>Date submitted: <i>{{ issue.date }}</i></p>
        <p>Type: <i>{{ issue.typeof }}</i></p>
        <p>Severity: <i>{{ issue.severity }}</i></p>
        <p>Status: <i>{{ issue.status }}</i></p>
        {% if issue.song.title != 'General' %}
        <p>Song: <i>{{ issue.song.title }}</i></p>
        {% endif %}
        <div class='description'><p>Description: <i>{{ issue.description }}</i></p></div>
        {% if not issue.minutes == 0 and issue.seconds == 0 %}
        <p>Time: {{ issue.minutes }}:{{ issue.seconds | stringformat:"02d" }}</p>
        {% endif %}
        {% if issue.song.url != '' %}
        <audio style="padding-top:20px;" controls id="song">
            <source src="{{ issue.song.url }}" type="audio/mpeg">
            Your browser does not support the audio element.
        </audio>
        {% endif %}
        <form style="padding-top:20px;" action="{% url 'issues:vote' issue.id %}" method="post">
            {% csrf_token %}
            <p>{{ issue.upvotes }}
            <button type='submit' title="{% for vote in upvoters %}{{ vote.user.username }} {% endfor %}" class="btn btn-success" name='voteup' value='+'><span class='glyphicon glyphicon-thumbs-up'></span></button>
            {{ issue.downvotes }}
            <button type='submit' title="{% for vote in downvoters %}{{ vote.user.username }} {% endfor %}"class="btn btn-danger" name='votedown' value='-'><span class='glyphicon glyphicon-thumbs-down'></span></button></p>
        </form>
        <form style="padding-top:20px;padding-bottom:20px;" action="{% url 'issues:comment' issue.id %}" method="post">
            {% csrf_token %}
            <div class="input-group">
                <input name="text" type="text" class="form-control" placeholder="Comment on this issue...">
                <span class="input-group-btn">
                    <button class="btn btn-primary" type="submit">Comment</button>
                </span>
            </div>
        </form>
        {% for comment in comments %}
        <div class="panel panel-default">
            <div class="panel-body">
                {{ comment.text }}
            </div>
            <div class="panel-footer">
                {{ comment.user }} | {{ comment.date }}
                {% if comment.user == user or user.is_superuser %}
                <a href="{% url 'issues:delete_comment' issue.id comment.id %}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                {% endif %}
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h1>Error. Not Implemented.</h1>
        {% endif %}
    </div>
</div>
{% endblock %}

issues/templates/issues/index.html
{% extends 'issues/base.html' %}
{% load staticfiles %}
{% block body %}
<script>
$( document ).ready(function() {
    $('#{{ page }}_nav').addClass('active');
});
</script>
<div class="list">
    {% if page == 'issues' %}
    <a href="{% url 'issues:new_issue' %}"<button type="button" class="btn btn-primary">New Issue</button></a>
    {% elif page == 'songs' %}
    <a href="{% url 'issues:new_song' %}"><button type="button" class="btn btn-primary">New Song</button></a>
    {% endif %}
    {% if issue_recent_list %}
    <div class="row" >
        <table class="table">
            <thead
                <tr>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Type</th>
                    <th>Song</th>
                    <th>Priority</th>
                    <th>Status</th>
                    <th>Date</th>
                    <th>User</th>
                    {% if user.is_superuser %}
                    <th>Actions</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for issue in issue_recent_list %}
                <tr>
                    <td><a href="{% url 'issues:detail' issue.id %}">{{ issue.title}}</a></td>
                    <td style="text-overflow: ellipsis; max-width: 180px;">{{ issue.description }}</td>
                    <td>{{ issue.typeof }}</td>
                    <td>{{ issue.song }}</td>
                    <td><span class="label label-{% if issue.severity == 'Trivial' %}info{% elif issue.severity = 'Minor' %}success{% elif issue.severity == 'Major' %}warning{% elif issue.severity == 'Severe' %}danger{% endif %}">{{ issue.severity }}</span></td>
                    <td><span class="label label-{% if issue.status == 'Resolved' %}info{% elif issue.status = 'Fix Proposed' %}success{% elif issue.status == 'Acknowledged' %}warning{% elif issue.status == 'New' %}danger{% endif %}">{{ issue.status }}</span></td>
                    <td>{{ issue.date }}</td>
                    <td>{{ issue.reporter }}</td>
                    {% if user.is_superuser %}
                    <td><a href="{% url 'issues:delete' issue.id %}"><span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span></a></td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
            {% elif song_recent_list %}
            <div class="issueTableList">
                <table class="table">
                    <thead>
                        <th>Title</th>
                        <th>Notes</th>
                        <th>URL</th>
                        {% if user.is_superuser %}
                        <th>Actions</th>
                        {% endif %}
                    </thead>
                    <tbody>
                    {% for song in song_recent_list %}
                    <tr>
                        <td><a href="{% url 'issues:song_detail' song.id %} ">{{ song.title }}</a></td>
                        <td>{{ song.notes }}</td>
                        <td><a href="{{ song.url }}">Link</a></td>
                        {% if user.is_superuser %}
                        <td><a href="{% url 'issues:delete_song' song.id %}"><span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span></a></td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                    </tbody>
                    {% else %}
                        <h3>There is nothing here. Yay!</h3>
                    {% endif %}
                </table>
            </div>
    </div>

    <div class='right'>
    </div>
    {% endblock %}

issues/templates/issues/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="/static/favicon.ico">

        <title>MOctoD Login</title>

        <!-- Bootstrap core CSS -->
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="{% static 'issues/login.css' %}" rel="stylesheet">

    </head>

    <body>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script>
$( document ).ready(function() {
    $("#{{ form.username.id_for_label }}").addClass("form-control");
    $("#{{ form.password.id_for_label }}").addClass("form-control");
    $("#{{ form.username.id_for_label }}").attr("placeholder", "Username");
    $("#{{ form.password.id_for_label }}").attr("placeholder", "Password");
});
        </script>
        <div class="container">

            <form class="form-signin" method="post" action="{% url 'issues:login' %}">
                <img style="margin-left:45px;margin-right:auto;margin-bottom:10px;" src="{% static 'issues/images/mod.png' %}"/>
                {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    <span class="sr-only">Error:</span>
                    Your username and password didn't match. Please try again.
                </div>
                {% endif %}
                {% csrf_token %}
                {{ form.username }}
                {{ form.password }}

                <input type="hidden" name="next" value="{{ next }}" />
                <button type="submit" class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
            </form>

        </div> <!-- /container -->

    </body>
</html>

issues/templates/issues/logout.html
{% load staticfiles %}
<div align='center'>
<link rel="stylesheet" type="text/css" href="{% static 'issues/style.css' %}"/>
<head>
    <title>MOctoD</title>
</head>
<body>
<header>
    <img src="{% static 'issues/images/mod.png' %}"/>
</header>
    <h3>Logged out</h3>
    <p>Thanks for spending some quality time with the website today.</p>
    <a href="{% url 'issues:login' %}">Log in again</a>
    </body>

issues/templates/issues/new.html
{% extends 'issues/base.html' %}
{% load staticfiles %}
{% block head %}
<head>
    <title>Create New {% if page == 'issue' %}Issue{% elif page == 'song' %}Song{% endif %} | MoD</title>
</head>
{% endblock %}
{% block body %}
<div class='details'>
    {% if page == 'issues' %}
    <h3>Create New Issue</h3>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <div class='new'>
    <br>
        <form id="create_form" action="" method="post">
            {% csrf_token %} 
            {{ form.errors }}
            {{ form.non_field_errors }}
            {{ form.title.errors }}
            <p><label for="{{ form.title.id_for_label }}">Title:</label>
            {{ form.title }}</p>
            <p><label for="{{ form.song.id_for_label }}">Song:</label>
            {{ form.song.errors }}
            {{ form.song }}</p>
            <p><label for="{{ form.typeof.id_for_label }}">Type:</label>
            {{ form.typeof.errors }}
            {{ form.typeof }}</p>
            <p><label for="{{ form.severity.id_for_label }}">Severity:</label>
            {{ form.severity.errors }}
            {{ form.severity }}</p>
            <p><label for="{{ form.description.id_for_label }}">Description:</label></p>
            {{ form.description.errors }}
            <p>{{ form.description }}</p>
            <p><label for="{{ form.minutes.id_for_label }}">Location in Song (Optional):</label> {{ form.minutes }}:{{ form.seconds }}</p>
            <button class="btn btn-primary" type='submit'>Submit</button>
        </form>
        {% else %}
        <h1>Error. Not Implemented.</h1>
        {% endif %}
        {% endblock %}

issues/templates/issues/newissue.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'issues/style.css' %}"/>
<head>
    <title>New Issue</title>
</head>
<body>
<header id='header'>
    <img src="{% static 'issues/images/mod.png' %}"/>
    <div class='top'>
        <ul>
            <a href="{% url 'issues:index' %}"><li>Issues</li></a>
            <a href="{% url 'issues:task_index' %}"><li>Tasks</li></a>
            <a href="{% url 'issues:song_index' %}"><li>Songs</li></a>
        </ul>
    </div>
</header>
<div class='details'>
<h3>Create New Issue</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<div class='new'>
<form action="" method="post">
    {% csrf_token %} {{ form.as_p }}
    <input type='submit' value='Submit'>
</form>
</body>
</html>

issues/templates/issues/settings.html
{% load staticfiles %}
{% extends 'issues/base.html' %}
{% block body %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
{% endblock %}